#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application('PHP Console Helper', '1.0');

// Add Faker Command
$app->add(new Pch\FakerCommand);
// Add Convert Commands
$app->addCommands(\Pch\ConvertCommand::getAll());

$app->run();